# Numpy Crash Course

In [2]:
import numpy as np

## Basics

### Basic Arrays

In [6]:
one_dimensional_array = np.array([1, 2, 3, 4, 5])
print(one_dimensional_array)

[1 2 3 4 5]


In [7]:
two_dimensional_array = np.array([[1, 2], [3, 4], [5, 6]])
print(two_dimensional_array)

[[1 2]
 [3 4]
 [5 6]]


### Sequences

In [5]:
sequence_of_integers = np.arange(1, 10)
print(sequence_of_integers)

[1 2 3 4 5 6 7 8 9]


### Random Numbers

In [8]:
random_integers = np.random.randint(low=50, high=101, size=6);
print(random_integers)

[61 56 92 79 86 93]


In [11]:
random_floats = np.random.random(6)
print(random_floats)

[0.50965773 0.63617858 0.02787952 0.34798326 0.42217977 0.76033235]


### Mathematical Operations

In [12]:
print(random_floats + 2)

[2.50965773 2.63617858 2.02787952 2.34798326 2.42217977 2.76033235]


In [13]:
print(random_integers * 3)

[183 168 276 237 258 279]


## Linear Dataset

Your goal is to create a simple dataset consisting of a single feature and a
label as follows:

1. Assign a sequence of integers from 6 to 20 (inclusive) to a NumPy array named
   `feature`.
1. Assign 15 values to a NumPy array named `label` such that
   `label = 3 * feature + 4`.

In [15]:
feature = np.arange(start=6, stop=21)
print(feature)

label = 3 * feature + 4
print(label)

[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[22 25 28 31 34 37 40 43 46 49 52 55 58 61 64]


To make your dataset a little more realistic, insert a little random noise into
each element of the `label` array you created. To be more precise, modify each
value assigned to `label` by adding a _different_ random floating-point value
between -2 and +2.

Don't rely on broadcasting. Instead, create a `noise` array having the same
dimension as `label`.

In [17]:
noise = np.random.random(len(label)) * 4 - 2
print(noise)

label = label + noise
print(label)

[ 0.29001493 -1.99834741 -0.60885187 -0.40047312 -0.27765964 -0.87504436
 -1.22775111 -0.02890938 -1.32788061  1.07176789  1.52164443 -1.14541473
 -0.68504407 -1.14134745 -1.50144741]
[22.29001493 23.00165259 27.39114813 30.59952688 33.72234036 36.12495564
 38.77224889 42.97109062 44.67211939 50.07176789 53.52164443 53.85458527
 57.31495593 59.85865255 62.49855259]
